<?php defined( 'ABSPATH' ) || exit; $drb_footer_options = drb_get_theme_options(); ?>
<footer class="drb-native-footer" role="contentinfo">
    <div class="drb-native-footer__inner">
        <div class="drb-native-footer__socials">
            <?php foreach ( array( 'instagram' => 'اینستاگرام', 'youtube' => 'یوتیوب', 'aparat' => 'آپارات', 'telegram' => 'تلگرام' ) as $drb_social_key => $drb_social_label ) : if ( empty( $drb_footer_options[ $drb_social_key ] ) ) continue; ?><a href="<?php echo esc_url( $drb_footer_options[ $drb_social_key ] ); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html( $drb_social_label ); ?></a><?php endforeach; ?>
        </div>
        <div class="drb-native-footer__grid">
            <section><div class="drb-native-footer__brand"><img src="<?php echo esc_url( DRB_THEME_URI . '/assets/dist6/logo-white.svg' ); ?>" alt="لوگو دکتر باستانی‌نژاد" width="36" height="36"><strong><?php echo esc_html( $drb_footer_options['doctor_name'] ); ?></strong></div><p>جراح و متخصص گوش، گلو و بینی<br>جراح پلاستیک بینی — تهران</p><div class="drb-native-footer__badges"><img src="<?php echo esc_url( DRB_THEME_URI . '/assets/dist6/images/enamad.webp' ); ?>" alt="نماد اعتماد" width="48" height="48"><img src="<?php echo esc_url( DRB_THEME_URI . '/assets/dist6/images/namad-n1.webp' ); ?>" alt="نشان انجمن" width="48" height="48"></div></section>
            <nav aria-label="لینک‌های سریع"><h2>لینک‌های سریع</h2><a href="<?php echo esc_url( home_url( '/about/' ) ); ?>">درباره دکتر</a><a href="<?php echo esc_url( home_url( '/gallery/' ) ); ?>">گالری قبل و بعد</a><a href="<?php echo esc_url( home_url( '/blog/' ) ); ?>">مقالات</a><a href="<?php echo esc_url( home_url( '/faq/' ) ); ?>">سوالات متداول</a><a href="<?php echo esc_url( home_url( '/booking/' ) ); ?>">رزرو نوبت</a></nav>
            <nav aria-label="خدمات"><h2>خدمات</h2><a href="<?php echo esc_url( home_url( '/services/rhinoplasty-primary/' ) ); ?>">جراحی بینی اولیه</a><a href="<?php echo esc_url( home_url( '/services/rhinoplasty-revision/' ) ); ?>">جراحی ترمیمی</a><a href="<?php echo esc_url( home_url( '/services/rhinoplasty-bony/' ) ); ?>">بینی استخوانی</a><a href="<?php echo esc_url( home_url( '/services/septoplasty/' ) ); ?>">اصلاح انحراف بینی</a><a href="<?php echo esc_url( home_url( '/services/' ) ); ?>">همه خدمات</a></nav>
            <section><h2>تماس با ما</h2><small>تلفن کلینیک</small><?php foreach ( array_slice( array_values( array_filter( preg_split( '/\R+/', $drb_footer_options['phones'] ) ) ), 0, 2 ) as $drb_phone ) : ?><a class="drb-native-footer__phone" href="tel:<?php echo esc_attr( preg_replace( '/\D+/', '', $drb_phone ) ); ?>"><?php echo esc_html( $drb_phone ); ?></a><?php endforeach; ?><small>ساعت پذیرش</small><p><?php echo esc_html( $drb_footer_options['clinic_hours'] ); ?></p><small>آدرس</small><p><?php echo esc_html( $drb_footer_options['address'] ); ?></p><div class="drb-native-map-links" aria-label="مسیریاب‌ها"><?php foreach ( array( array( 'Google Maps', 'https://maps.google.com/?q=35.758881,51.413824', 'GoogleMap.webp' ), array( 'نشان', 'https://nshn.ir/gNbNgYZt_Rxg', 'Neshan.webp' ), array( 'بلد', 'https://balad.ir/p/3cuwGGif58f8hT', 'Balad.webp' ), array( 'Waze', 'https://waze.com/ul/htnke3vwqs', 'Waze.webp' ) ) as $drb_map ) : ?><a href="<?php echo esc_url( $drb_map[1] ); ?>" target="_blank" rel="noopener" title="<?php echo esc_attr( $drb_map[0] ); ?>"><img src="<?php echo esc_url( DRB_THEME_URI . '/assets/dist6/images/Icons/' . $drb_map[2] ); ?>" alt="<?php echo esc_attr( $drb_map[0] ); ?>" width="20" height="20"></a><?php endforeach; ?></div></section>
        </div>
        <nav class="drb-native-footer__legal" aria-label="پیوندهای حقوقی"><a href="<?php echo esc_url( home_url( '/legal/privacy/' ) ); ?>">سیاست حریم خصوصی</a><a href="<?php echo esc_url( home_url( '/legal/terms/' ) ); ?>">شرایط استفاده</a><a href="<?php echo esc_url( home_url( '/legal/cancellation/' ) ); ?>">سیاست لغو</a><a href="<?php echo esc_url( home_url( '/sitemap/' ) ); ?>">نقشه سایت</a></nav>
        <div class="drb-native-footer__bottom"><span>© <?php echo esc_html( wp_date( 'Y' ) ); ?> کلینیک <?php echo esc_html( $drb_footer_options['doctor_name'] ); ?> — تمامی حقوق محفوظ است.</span><span>طراحی توسط <a href="https://maziyarid.com" target="_blank" rel="noopener">MAZ</a></span></div>
    </div>
</footer>
