(()=>{'use strict';
const C=window.TAJ_EN_CONFIG||{},$=id=>document.getElementById(id);
const state={step:1,method:'',token:'',verified:false,verifiedUntil:0,timer:null,signatureEmpty:true};
const regionCodes='AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW'.split(' ');
const countryNames={IR:'Iran',GB:'United Kingdom',US:'United States',CA:'Canada',AU:'Australia',DE:'Germany',FR:'France',IT:'Italy',ES:'Spain',TR:'Türkiye',AE:'United Arab Emirates',QA:'Qatar',KW:'Kuwait',SA:'Saudi Arabia',OM:'Oman',IQ:'Iraq',AF:'Afghanistan',IN:'India',PK:'Pakistan'};
const dn=typeof Intl!=='undefined'&&Intl.DisplayNames?new Intl.DisplayNames(['en'],{type:'region'}):null;
regionCodes.forEach(code=>{const o=document.createElement('option');o.value=code;o.textContent=(countryNames[code]||(dn?dn.of(code):code));$('country').appendChild(o)});
$('birth-date').max=new Date().toISOString().slice(0,10);
function toast(m,t=''){const e=$('toast');e.textContent=m;e.className='toast show'+(t?' '+t:'');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),5200)}
function error(el,msg){const f=el.closest('.field');if(f){f.classList.add('invalid');const x=f.querySelector('.error');if(x)x.textContent=msg}}
function clear(el){const f=el.closest('.field');if(f){f.classList.remove('invalid');const x=f.querySelector('.error');if(x)x.textContent=''}}
function normalisePhone(v,country){let s=String(v||'').trim().replace(/[\s().-]/g,'');if(s.startsWith('00'))s='+'+s.slice(2);if(country==='IR'&&/^09\d{9}$/.test(s))s='+98'+s.slice(1);return s}
function validPhone(v,country){return /^\+[1-9]\d{7,14}$/.test(normalisePhone(v,country))}
function isIranMobile(v,c){return c==='IR'&&/^\+989\d{9}$/.test(normalisePhone(v,c))}
function validIranId(code){if(!/^\d{10}$/.test(code)||/^(\d)\1{9}$/.test(code))return false;let sum=0;for(let i=0;i<9;i++)sum+=Number(code[i])*(10-i);const r=sum%11,ch=Number(code[9]);return r<2?ch===r:ch===11-r}
const passportPatterns={IR:/^[A-Z]\d{8}$/,GB:/^\d{9}$/,US:/^(?:\d{9}|[A-Z]\d{8})$/,CA:/^(?:[A-Z]{2}\d{6}|[A-Z]\d{6}[A-Z]{2})$/,AU:/^[A-Z]\d{7}$/,DE:/^[CFGHJKLMNPRTVWXYZ0-9]{9}$/,FR:/^\d{2}[A-Z]{2}\d{5}$/,IN:/^[A-Z]\d{7}$/,PK:/^[A-Z]{2}\d{7}$/,TR:/^[A-Z]\d{8}$/,AE:/^[A-Z0-9]{5,20}$/};
function identityOk(v,c){const x=String(v||'').toUpperCase().replace(/[\s-]+/g,'');if(c==='IR'&&/^\d{10}$/.test(x))return validIranId(x);const p=passportPatterns[c];return p?p.test(x):/^[A-Z0-9]{5,20}$/.test(x)}
function setVerificationText(){const c=$('country').value,p=$('verification-phone').value;if(c&&validPhone(p,c)&&isIranMobile(p,c))$('verification-method-text').textContent='We’ll send a verification code by SMS.';else if(c&&validPhone(p,c))$('verification-method-text').textContent='Use your device’s secure unlock method (Face ID, fingerprint, device PIN, or passkey) to continue.';else $('verification-method-text').textContent='Enter your mobile number to continue.'}
['country','verification-phone'].forEach(id=>$(id).addEventListener('input',()=>{resetVerification();setVerificationText()}));
function resetVerification(){state.method='';state.token='';state.verified=false;state.verifiedUntil=0;if(state.timer)clearInterval(state.timer);$('verification-status').textContent='';$('verification-status').className='status';$('verification-timer').classList.add('hidden');$('sms-code-wrap').classList.add('hidden');$('verify-code-btn').classList.add('hidden');$('verify-start-btn').classList.remove('hidden');$('verify-start-btn').textContent='Start verification';$('verify-code-btn').textContent='Confirm code'}
function validIdentityStep(){let ok=true;[['first-name','Enter your first name.'],['last-name','Enter your last name.'],['country','Select your country.']].forEach(([id,m])=>{const e=$(id);if(!e.value.trim()){error(e,m);ok=false}else clear(e)});const p=$('verification-phone'),c=$('country').value;if(!validPhone(p.value,c)){error(p,'Enter a valid mobile number with country code, e.g. +44 7700 900123.');ok=false}else clear(p);return ok}
async function api(url,payload){const r=await fetch(url,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify(payload)});let d={};try{d=await r.json()}catch(e){}if(!r.ok||d.success===false)throw new Error(d.message||`Request failed (HTTP ${r.status})`);return d}
function b64ToBytes(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const b=atob(s),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return a}
function bytesToB64(buf){const a=new Uint8Array(buf);let s='';for(const x of a)s+=String.fromCharCode(x);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function publicKeyOptions(o){const p=JSON.parse(JSON.stringify(o));p.challenge=b64ToBytes(p.challenge);if(p.user&&p.user.id)p.user.id=b64ToBytes(p.user.id);if(p.allowCredentials)p.allowCredentials=p.allowCredentials.map(x=>({...x,id:b64ToBytes(x.id)}));if(p.excludeCredentials)p.excludeCredentials=p.excludeCredentials.map(x=>({...x,id:b64ToBytes(x.id)}));return p}
function serialiseCredential(c){const r={id:c.id,type:c.type,rawId:bytesToB64(c.rawId),response:{clientDataJSON:bytesToB64(c.response.clientDataJSON)}};if(c.response.attestationObject)r.response.attestationObject=bytesToB64(c.response.attestationObject);if(c.response.authenticatorData)r.response.authenticatorData=bytesToB64(c.response.authenticatorData);if(c.response.signature)r.response.signature=bytesToB64(c.response.signature);if(c.response.userHandle)r.response.userHandle=bytesToB64(c.response.userHandle);return r}
function startTimer(sec){state.verified=true;state.verifiedUntil=Date.now()+Number(sec||1800)*1000;$('verification-timer').classList.remove('hidden');if(state.timer)clearInterval(state.timer);const tick=()=>{const left=Math.max(0,Math.ceil((state.verifiedUntil-Date.now())/1000)),m=String(Math.floor(left/60)).padStart(2,'0'),s=String(left%60).padStart(2,'0');$('verification-timer-value').textContent=`${m}:${s}`;if(left<=0){resetVerification();$('verification-status').textContent='Verification expired. Please verify again.';$('verification-status').className='status error'}};tick();state.timer=setInterval(tick,1000)}
$('verify-start-btn').addEventListener('click',async()=>{if(!validIdentityStep())return;const c=$('country').value,p=normalisePhone($('verification-phone').value,c),btn=$('verify-start-btn');btn.disabled=true;try{if(isIranMobile(p,c)){const d=await api(C.OTP_SEND_URL,{phone:p,country:c});state.method='sms';state.token=d.token;$('sms-code-wrap').classList.remove('hidden');$('verify-code-btn').classList.remove('hidden');$('verify-start-btn').classList.add('hidden');$('verification-status').textContent=d.message||'Verification code sent.';toast('Verification code sent.','ok')}else{if(!window.PublicKeyCredential||!navigator.credentials)throw new Error('Secure verification is not available in this browser. Please use a current browser on a device with Face ID, fingerprint, a device PIN, or a passkey.');const a=await api(C.DEVICE_REGISTER_OPTIONS_URL,{phone:p,country:c,displayName:($('first-name').value+' '+$('last-name').value).trim()});state.token=a.token;const cred=await navigator.credentials.create({publicKey:publicKeyOptions(a.publicKey)});await api(C.DEVICE_REGISTER_URL,{token:state.token,credential:serialiseCredential(cred)});const b=await api(C.DEVICE_ASSERT_OPTIONS_URL,{token:state.token});const assertion=await navigator.credentials.get({publicKey:publicKeyOptions(b.publicKey)});const done=await api(C.DEVICE_ASSERT_URL,{token:state.token,credential:serialiseCredential(assertion)});state.method='device';startTimer(done.expiresIn);$('verification-status').textContent=done.message||'Verification complete.';$('verification-status').className='status ok';$('verify-start-btn').textContent='Verified ✓';toast('Verification complete.','ok')}}catch(e){const raw=String(e?.message||'Verification could not be completed.');const msg=/authenticator|credential|cbor|rp id|public key|device-verification|browser authentication|attested/i.test(raw)?'Secure verification could not be completed. Please try again or use another current browser or device.':raw;$('verification-status').textContent=msg;$('verification-status').className='status error';toast(msg,'error')}finally{btn.disabled=false}});
$('verify-code-btn').addEventListener('click',async()=>{const code=$('verification-code').value.replace(/\D/g,'');if(!/^\d{4,6}$/.test(code)){error($('verification-code'),'Enter the 4–6 digit code.');return}clear($('verification-code'));const b=$('verify-code-btn');b.disabled=true;try{const d=await api(C.OTP_VERIFY_URL,{phone:normalisePhone($('verification-phone').value,$('country').value),country:$('country').value,token:state.token,code});state.method='sms';startTimer(d.expiresIn);$('verification-status').textContent=d.message||'Phone verified.';$('verification-status').className='status ok';b.textContent='Verified ✓';toast('Phone number verified.','ok')}catch(e){toast(e.message,'error')}finally{b.disabled=false}});
function go(n){document.querySelectorAll('.step').forEach(x=>x.classList.remove('active'));$(`step-${n}`).classList.add('active');[1,2,3].forEach(i=>{const p=$(`p${i}`);p.classList.toggle('active',i===n);p.classList.toggle('done',i<n)});state.step=n;if(n===3)setTimeout(()=>signature.resize(true),40);window.scrollTo({top:0,behavior:'smooth'})}
$('next-1').addEventListener('click',()=>{if(!validIdentityStep())return;if(!state.verified||Date.now()>state.verifiedUntil){toast('Complete verification before continuing.','error');return}go(2)});$('prev-2').addEventListener('click',()=>go(1));$('prev-3').addEventListener('click',()=>go(2));
function required(id,msg){const e=$(id);if(!String(e.value||'').trim()){error(e,msg);return false}clear(e);return true}
function validOptionalPhone(id){const e=$(id);if(!e.value.trim()){clear(e);return true}if(!validPhone(e.value,$('country').value)){error(e,'Include the country code, for example +44 7700 900123.');return false}clear(e);return true}
function validStep2(){let ok=true;[['father-name',"Enter the patient's father's name."],['occupation','Select an occupation.'],['identity-document','Enter a passport or national identity number.'],['birth-date','Enter a date of birth.'],['address','Enter the full address.'],['visit-reason','Select the reason for appointment.'],['referral','Select how you heard about the clinic.']].forEach(([id,m])=>{if(!required(id,m))ok=false});const ident=$('identity-document');if(ident.value&& !identityOk(ident.value,$('country').value)){error(ident,'Please check the passport or identity number and the selected country.');ok=false}if($('birth-date').value){const d=new Date($('birth-date').value+'T12:00:00Z');if(Number.isNaN(d.getTime())||$('birth-date').value>new Date().toISOString().slice(0,10)){error($('birth-date'),'Enter a valid date of birth.');ok=false}}['home-phone','emergency-phone','referrer-phone'].forEach(id=>{if(!validOptionalPhone(id))ok=false});if($('emergency-phone').value&&normalisePhone($('emergency-phone').value,$('country').value)===normalisePhone($('verification-phone').value,$('country').value)){error($('emergency-phone'),'Emergency phone must differ from the patient phone.');ok=false}return ok}
$('next-2').addEventListener('click',()=>{if(validStep2())go(3)});
const signature=(()=>{const canvas=$('signature-pad'),ctx=canvas.getContext('2d',{alpha:false});let drawing=false,last=null,empty=true;function resize(preserve=true){const r=canvas.getBoundingClientRect();if(r.width<20)return;const old=preserve&&!empty?canvas.toDataURL('image/png'):'';const ratio=Math.min(3,Math.max(1,devicePixelRatio||1));canvas.width=Math.round(r.width*ratio);canvas.height=Math.round(170*ratio);ctx.setTransform(ratio,0,0,ratio,0,0);ctx.fillStyle='#fff';ctx.fillRect(0,0,r.width,170);ctx.strokeStyle='#17211a';ctx.lineWidth=2.4;ctx.lineCap='round';if(old){const im=new Image();im.onload=()=>ctx.drawImage(im,0,0,r.width,170);im.src=old}}function pos(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}canvas.addEventListener('pointerdown',e=>{e.preventDefault();drawing=true;empty=false;last=pos(e);canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drawing)return;e.preventDefault();const n=pos(e);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(n.x,n.y);ctx.stroke();last=n});['pointerup','pointercancel','pointerleave'].forEach(t=>canvas.addEventListener(t,()=>{drawing=false;last=null}));$('clear-signature').addEventListener('click',()=>{empty=true;resize(false)});window.addEventListener('resize',()=>resize(true));return{resize,isEmpty:()=>empty,data:()=>empty?'':canvas.toDataURL('image/png')}})();
function buildDescription(){const parts=[`Visit reason: ${$('visit-reason').value}`,`Request for doctor: ${$('doctor-request').value.trim()}`];if($('condition-details').value.trim())parts.push(`Other medical details: ${$('condition-details').value.trim()}`);if($('insurance').value.trim())parts.push(`Insurance: ${$('insurance').value.trim()}`);return parts.join(' | ')}
function payload(){const c=$('country').value;return{FirstName:$('first-name').value.trim(),LastName:$('last-name').value.trim(),FatherName:$('father-name').value.trim(),TavalodDay:'',TavalodMonth:'',TavalodYear:'',BirthDateGregorian:$('birth-date').value,HomeTel:$('home-phone').value.trim(),Mobile:normalisePhone($('verification-phone').value,c),Mobile2:$('emergency-phone').value.trim(),CodeAshnaei:$('referral').value,CodeBimeh:'1',CodeMeli:$('identity-document').value.trim(),CodeJob:$('occupation').value,HomeAd:$('address').value.trim(),Description:buildDescription(),IsTransfer:'0',drugs:Array.from(document.querySelectorAll('.drug-chk:checked')).map(x=>x.value).join('/'),difficult:Array.from(document.querySelectorAll('.med-hist:checked')).map(x=>x.value).join('/'),morefmob:$('referrer-phone').value.trim(),Country:c,_website:$('website-field').value,_source:location.href,_meta:{verificationMethod:state.method,verificationToken:state.token,signature:signature.data(),countryName:$('country').selectedOptions[0]?.textContent||c,email:$('patient-email').value.trim()}}}
$('patient-form').addEventListener('submit',async e=>{e.preventDefault();if(!state.verified||Date.now()>state.verifiedUntil){toast('Verification has expired. Please verify again.','error');go(1);return}let ok=required('doctor-request','Please describe what you would like to discuss with the doctor.');const email=$('patient-email');if(email.value&&!email.validity.valid){error(email,'Enter a valid email address.');ok=false}else clear(email);if(!$('confirmation-check').checked){$('consent-error').textContent='Consent is required.';ok=false}else $('consent-error').textContent='';if(signature.isEmpty()){toast('Please provide your signature.','error');ok=false}if(!ok)return;const b=$('submit-btn');b.disabled=true;b.textContent='Submitting…';try{const d=await api(C.SUBMIT_URL,payload());$('patient-form').classList.add('hidden');document.querySelector('.progress').classList.add('hidden');$('success-panel').classList.remove('hidden');$('success-message').textContent=d.reference?`Thank you. Your registration has been received. Reference: ${d.reference}.`:'Thank you. Your registration has been received.';toast('Registration submitted.','ok')}catch(err){toast(err.message,'error')}finally{b.disabled=false;b.textContent='Submit patient registration'}});
fetch(C.HEALTH_URL,{headers:{Accept:'application/json'}}).then(r=>r.json()).then(d=>{if(!d.ok)throw new Error('Registration is temporarily unavailable.')}).catch(e=>{$('api-warning').textContent='Registration is temporarily unavailable. Please try again shortly.';$('api-warning').classList.remove('hidden')});
setVerificationText();setTimeout(()=>signature.resize(false),50);
})();
