/* MAZ//ID · © 2026 Maziyar / Dr. Shahin Bastaninejad — synthetic DOM QA */
import assert from 'node:assert/strict';
const { JSDOM } = await import(process.env.JSDOM_MODULE || 'jsdom');
const { mountRecorderPanel, renderDraftTurns } = await import('../assets/js/recording/panel.js');
const { createDraft } = await import('../assets/js/recording/session.js');
const dom = new JSDOM('<!doctype html><html dir="rtl" lang="fa"><body><main><div id="recorder"></div><div id="turns"></div></main></body></html>');
const document = dom.window.document;
const host = document.querySelector('#recorder'); mountRecorderPanel(host, { patientId: '42' });
assert.equal(host.querySelectorAll('button').length, 5);
assert.equal(host.querySelectorAll('button:enabled').length, 0);
assert.equal(host.querySelectorAll('input[type=checkbox]:disabled').length, 1);
assert.match(host.textContent, /هنوز فعال نشده/);
assert.equal(host.querySelectorAll('[role=status]').length, 1);
const turns = document.querySelector('#turns');
const draft = createDraft({ sessionId: 'synthetic-session', audioDurationMs: 1000, provider: { name: 'synthetic', version: '1' }, segments: [{ id: 'turn-1', startMs: 0, endMs: 1000, speakerId: null, text: '<img src=x onerror="window.attacked=true"> متن ساختگی' }] });
let latest = draft; renderDraftTurns(turns, draft, { actorId: '9', onChange: value => { latest = value; } });
assert.equal(turns.querySelectorAll('img').length, 0); assert.equal(dom.window.attacked, undefined);
assert.match(turns.textContent, /گوینده نامشخص/);
turns.querySelector('select').value = 'doctor'; turns.querySelector('input').value = 'پزشک ساختگی';
[...turns.querySelectorAll('button')].find(button => button.textContent === 'ثبت دستی گوینده').click();
assert.equal(latest.segments[0].speaker.role, 'doctor');
turns.querySelector('textarea').value = 'متن اصلاح‌شده ساختگی';
[...turns.querySelectorAll('button')].find(button => button.textContent === 'ثبت اصلاح متن').click();
assert.equal(latest.segments[0].text, 'متن اصلاح‌شده ساختگی');
assert.equal(latest.reviewStatus, 'unreviewed'); assert.equal(latest.segments[0].rawText, draft.segments[0].rawText);
assert.equal(latest.segments[0].speaker.role, 'doctor');
assert.equal(host.querySelectorAll('a[href]').length, 0);
console.log('PASS: DOM fail-closed controls, named consent, literal unsafe text, manual speaker assignment and transcript correction');
dom.window.close();
