<?php
declare(strict_types=1);

namespace App\Core;

/**
 * Request — HTTP request value object.
 *
 * JSON remains the default write transport. The only multipart exception is
 * the bounded, authenticated recorder chunk route; it is intentionally narrow
 * so increasing recorder capacity cannot expand every API request.
 */
final class Request
{
    public string  $method;
    public string  $path;
    public array   $body;
    public array   $query;
    public array   $headers;
    public array   $files = [];
    public array   $params = [];
    public ?array  $user = null;

    public static function fromGlobals(): self
    {
        $req = new self();

        $req->method = strtoupper($_SERVER['REQUEST_METHOD'] ?? 'GET');

        $uri = $_SERVER['REQUEST_URI'] ?? '/';
        $path = parse_url($uri, PHP_URL_PATH) ?? '/';
        $req->path = '/' . trim($path, '/');
        if ($req->path === '') {
            $req->path = '/';
        }

        parse_str($_SERVER['QUERY_STRING'] ?? '', $qs);
        $req->query = $qs;

        $headers = [];
        foreach ($_SERVER as $key => $value) {
            if (str_starts_with($key, 'HTTP_')) {
                $name = strtolower(str_replace('_', '-', substr($key, 5)));
                $headers[$name] = $value;
            }
        }
        if (isset($_SERVER['CONTENT_TYPE'])) {
            $headers['content-type'] = $_SERVER['CONTENT_TYPE'];
        }
        if (isset($_SERVER['CONTENT_LENGTH'])) {
            $headers['content-length'] = $_SERVER['CONTENT_LENGTH'];
        }
        $req->headers = $headers;
        $req->body = [];
        $req->files = [];

        if (in_array($req->method, ['POST', 'PUT', 'PATCH', 'DELETE'], true)) {
            $contentType = strtolower(trim(explode(';', (string)($headers['content-type'] ?? ''))[0]));
            if ($contentType === 'multipart/form-data') {
                if (!self::isRecordingChunkPath($req->path) || $req->method !== 'POST') {
                    throw new \RuntimeException('Unsupported multipart request');
                }
                $maxBytes = max(262144, (int)($_ENV['RECORDING_CHUNK_REQUEST_MAX_BYTES'] ?? 3145728));
                $length = (int)($headers['content-length'] ?? 0);
                if ($length > $maxBytes) {
                    throw new \RuntimeException('Recording chunk too large');
                }
                $req->body = is_array($_POST) ? $_POST : [];
                $req->files = self::normaliseFiles($_FILES ?? []);
            } else {
                $maxBytes = max(1024, (int)($_ENV['MAX_BODY_BYTES'] ?? 65536));
                $length = (int)($headers['content-length'] ?? 0);
                if ($length > $maxBytes) {
                    throw new \RuntimeException('Request body too large');
                }
                $raw = file_get_contents('php://input', false, null, 0, $maxBytes + 1);
                if (is_string($raw) && strlen($raw) > $maxBytes) {
                    throw new \RuntimeException('Request body too large');
                }
                if ($raw !== false && $raw !== '') {
                    $req->body = self::decodeJsonBody($raw);
                }
            }
        }

        return $req;
    }

    public static function decodeJsonBody(string $raw): array
    {
        $raw = trim($raw);
        if ($raw === '') {
            return [];
        }
        try {
            $decoded = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $e) {
            throw new \RuntimeException('Malformed JSON', 0, $e);
        }
        if (!is_array($decoded)) {
            throw new \RuntimeException('Malformed JSON');
        }
        return $decoded;
    }

    private static function isRecordingChunkPath(string $path): bool
    {
        return preg_match(
            '#^/api/v1/patients/[1-9][0-9]{0,15}/recording-sessions/[a-f0-9]{32}/chunks/[0-9]{1,4}$#i',
            $path
        ) === 1;
    }

    /**
     * Copy only scalar PHP upload metadata. tmp_name is generated by PHP;
     * original name/type remain untrusted and are never used as storage paths.
     *
     * @param array<string,mixed> $files
     * @return array<string,array{name:string,type:string,tmp_name:string,error:int,size:int}>
     */
    private static function normaliseFiles(array $files): array
    {
        $out = [];
        foreach ($files as $field => $file) {
            if (!is_string($field) || !is_array($file)) {
                continue;
            }
            foreach (['name', 'type', 'tmp_name', 'error', 'size'] as $key) {
                if (!array_key_exists($key, $file) || is_array($file[$key])) {
                    continue 2;
                }
            }
            $out[$field] = [
                'name' => (string)$file['name'],
                'type' => (string)$file['type'],
                'tmp_name' => (string)$file['tmp_name'],
                'error' => (int)$file['error'],
                'size' => (int)$file['size'],
            ];
        }
        return $out;
    }
}
